repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        files: \.(js|rb|md|py|sh|txt|yaml|yml|kidm)$

  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        entry: uvx --with mdformat-gfm --with mdformat-frontmatter mdformat --wrap 100 --number
        language: system
        types: [markdown]
        pass_filenames: true

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uvx ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
      - id: ruff-format
        name: ruff-format
        entry: uvx ruff format
        language: system
        types: [python]
        pass_filenames: true
      - id: ty
        name: ty
        entry: uvx ty check
        language: system
        types: [python]
        pass_filenames: false
